name: Andrew Hall
favicon: null
layout_spectrum: 0.916310686385259
typography_spectrum: 0.8155551119707525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8327582716010511
  lightness: 0.039143954403698444
  saturation: 0.41537666344083846
  rhythmicContrast: 0.15383727848529816
purpose: []
